export const SOLO_SONGS = [
  { id: "demo-1", title: "Bohemian Rhapsody", artist: "Queen", year: "1975" },
  { id: "demo-2", title: "Billie Jean", artist: "Michael Jackson", year: "1982" },
  { id: "demo-3", title: "Like a Prayer", artist: "Madonna", year: "1989" },
  { id: "demo-4", title: "Smells Like Teen Spirit", artist: "Nirvana", year: "1991" },
  { id: "demo-5", title: "Wonderwall", artist: "Oasis", year: "1995" },
  { id: "demo-6", title: "Wannabe", artist: "Spice Girls", year: "1996" },
  { id: "demo-7", title: "Baby One More Time", artist: "Britney Spears", year: "1998" },
  { id: "demo-8", title: "Hey Ya", artist: "OutKast", year: "2003" },
  { id: "demo-9", title: "Crazy in Love", artist: "Beyonce", year: "2003" },
  { id: "demo-10", title: "Hips Don't Lie", artist: "Shakira", year: "2006" },
  { id: "demo-11", title: "Umbrella", artist: "Rihanna", year: "2007" },
  { id: "demo-12", title: "Poker Face", artist: "Lady Gaga", year: "2008" },
  { id: "demo-13", title: "Rolling in the Deep", artist: "Adele", year: "2011" },
  { id: "demo-14", title: "Happy", artist: "Pharrell Williams", year: "2013" },
  { id: "demo-15", title: "Shake It Off", artist: "Taylor Swift", year: "2014" },
  { id: "demo-16", title: "Uptown Funk", artist: "Mark Ronson", year: "2014" },
  { id: "demo-17", title: "Shape of You", artist: "Ed Sheeran", year: "2017" },
  { id: "demo-18", title: "Old Town Road", artist: "Lil Nas X", year: "2019" },
  { id: "demo-19", title: "Blinding Lights", artist: "The Weeknd", year: "2019" },
  { id: "demo-20", title: "Levitating", artist: "Dua Lipa", year: "2020" },
  { id: "demo-21", title: "Flowers", artist: "Miley Cyrus", year: "2023" },
  { id: "demo-22", title: "Sweet Dreams", artist: "Eurythmics", year: "1983" },
];
