export const songs = [
  { id: "demo-1", title: "Bohemian Rhapsody", artist: "Queen", year: "1975", previewUrl: null, image: null },
  { id: "demo-2", title: "Billie Jean", artist: "Michael Jackson", year: "1982", previewUrl: null, image: null },
  { id: "demo-3", title: "Like a Prayer", artist: "Madonna", year: "1989", previewUrl: null, image: null },
  { id: "demo-4", title: "Smells Like Teen Spirit", artist: "Nirvana", year: "1991", previewUrl: null, image: null },
  { id: "demo-5", title: "Wonderwall", artist: "Oasis", year: "1995", previewUrl: null, image: null },
  { id: "demo-6", title: "Wannabe", artist: "Spice Girls", year: "1996", previewUrl: null, image: null },
  { id: "demo-7", title: "…Baby One More Time", artist: "Britney Spears", year: "1998", previewUrl: null, image: null },
  { id: "demo-8", title: "Hey Ya!", artist: "OutKast", year: "2003", previewUrl: null, image: null },
  { id: "demo-9", title: "Crazy in Love", artist: "Beyoncé", year: "2003", previewUrl: null, image: null },
  { id: "demo-10", title: "Hips Don't Lie", artist: "Shakira", year: "2006", previewUrl: null, image: null },
  { id: "demo-11", title: "Umbrella", artist: "Rihanna", year: "2007", previewUrl: null, image: null },
  { id: "demo-12", title: "Poker Face", artist: "Lady Gaga", year: "2008", previewUrl: null, image: null },
  { id: "demo-13", title: "Rolling in the Deep", artist: "Adele", year: "2011", previewUrl: null, image: null },
  { id: "demo-14", title: "Blurred Lines", artist: "Robin Thicke", year: "2013", previewUrl: null, image: null },
  { id: "demo-15", title: "Happy", artist: "Pharrell Williams", year: "2013", previewUrl: null, image: null },
  { id: "demo-16", title: "Shake It Off", artist: "Taylor Swift", year: "2014", previewUrl: null, image: null },
  { id: "demo-17", title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", year: "2014", previewUrl: null, image: null },
  { id: "demo-18", title: "Shape of You", artist: "Ed Sheeran", year: "2017", previewUrl: null, image: null },
  { id: "demo-19", title: "Old Town Road", artist: "Lil Nas X", year: "2019", previewUrl: null, image: null },
  { id: "demo-20", title: "Blinding Lights", artist: "The Weeknd", year: "2019", previewUrl: null, image: null },
  { id: "demo-21", title: "Levitating", artist: "Dua Lipa", year: "2020", previewUrl: null, image: null },
  { id: "demo-22", title: "Flowers", artist: "Miley Cyrus", year: "2023", previewUrl: null, image: null },
];
